name: DreamRealms
version: '${version}'
main: cn.mcloli.dreamrealms.DreamRealms
api-version: 1.13
depend: []
softdepend: 
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - CraftEngine
  - ItemsAdder
  - SweetMail
  - GlobalMarketPlus
  - zAuctionHouse
authors: [ LectWolf ]
folia-supported: true
commands:
  dreamrealms:
    description: 'The main command of DreamRealms'
    aliases: [ dr ]
